INSERT INTO "public"."jargon_entry" ("type", "value") VALUES ('TECH_ADJECTIVE', 'Advanced');
INSERT INTO "public"."jargon_entry" ("type", "value") VALUES ('TECH_ADJECTIVE', 'Scalable');
INSERT INTO "public"."jargon_entry" ("type", "value") VALUES ('TECH_ADJECTIVE', 'Robust');
INSERT INTO "public"."jargon_entry" ("type", "value") VALUES ('JVM_TECH', 'Scala');
INSERT INTO "public"."jargon_entry" ("id", "type", "value") VALUES (DEFAULT, 'JVM_TECH', 'Kotlin');
INSERT INTO "public"."jargon_entry" ("type", "value") VALUES ('JVM_TECH', 'Groovy');
INSERT INTO "public"."jargon_entry" ("type", "value") VALUES ('JVM_TECH', 'Java');
INSERT INTO "public"."jargon_entry" ("type", "value") VALUES ('SUB_TECH_TYPE', 'Logging');
INSERT INTO "public"."jargon_entry" ("type", "value") VALUES ('SUB_TECH_TYPE', 'Data Pipelines');
INSERT INTO "public"."jargon_entry" ("type", "value") VALUES ('SUB_TECH_TYPE', 'Search');
INSERT INTO "public"."jargon_entry" ("type", "value") VALUES ('SUB_TECH_TYPE', 'SEO');
INSERT INTO "public"."jargon_entry" ("type", "value") VALUES ('SUB_TECH_TYPE', 'AI');
INSERT INTO "public"."jargon_entry" ("type", "value") VALUES ('SUB_TECH_TYPE', 'Machine Learning');
INSERT INTO "public"."jargon_entry" ("type", "value") VALUES ('SIZE_ADJECTIVE', 'massive');
INSERT INTO "public"."jargon_entry" ("id", "type", "value") VALUES (DEFAULT, 'SIZE_ADJECTIVE', 'huge');
INSERT INTO "public"."jargon_entry" ("type", "value") VALUES ('SIZE_ADJECTIVE', 'fear-inducing');
INSERT INTO "public"."jargon_entry" ("type", "value") VALUES ('SIZE_ADJECTIVE', 'threatening levels of');
INSERT INTO "public"."jargon_entry" ("type", "value") VALUES ('VALUE', 'value');
INSERT INTO "public"."jargon_entry" ("type", "value") VALUES ('VALUE', 'profit');
INSERT INTO "public"."jargon_entry" ("type", "value") VALUES ('VALUE', 'satisfaction');
INSERT INTO "public"."jargon_entry" ("type", "value") VALUES ('TYPE_ORGANIZATION', 'Enterprise');
INSERT INTO "public"."jargon_entry" ("type", "value") VALUES ('TYPE_ORGANIZATION', 'Organization');
INSERT INTO "public"."jargon_entry" ("type", "value") VALUES ('TYPE_ORGANIZATION', 'Business');
